import "./globals.css";

export const metadata = {
  title: 'Curator',
  description: 'Generated by Joseph Jojoe and Jessica Ye!',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
